# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/david/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="kardan"

# mémo: af-magic muse trapd00r kardan

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
#ZSH_THEME_RANDOM_CANDIDATES=( "af-magic" "muse" "trapd00r" "kardan" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git cp)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"


## Raccourcis
alias ADS="cd /run/media/david/Cours/BA4_ADS"
alias GEN="cd /run/media/david/Cours/BA4_GEN"
alias PCO="cd /run/media/david/Cours/BA4_PCO"
alias PRO="cd /run/media/david/Cours/BA4_PRO"
alias RES="cd /run/media/david/Cours/BA4_RES"
alias SER="cd /run/media/david/Cours/BA4_SER"
alias SLO="cd /run/media/david/Cours/BA4_SLO"
alias SOS="cd /run/media/david/Cours/BA4_SOS"
alias SRX="cd /run/media/david/Cours/BA4_SRX"
# Autres
alias CTF="cd /run/media/david/Cours/Divers/CTFs"
alias BCK="cd /run/media/david/Cours/.backups"


## Faces https://textfac.es/
alias lennyf='echo -n "( ͡° ͜ʖ ͡°)" | xclip -selection c'
alias dunnof='echo -n "¯\_(ツ)_/¯" | xclip -selection c'
alias kawaiif='echo -n "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧" | xclip -selection c'
alias cryf='echo -n "ಥ_ಥ" | xclip -selection c'
alias tablef='echo -n "(╯°□°）╯︵ ┻━┻" | xclip -selection c'
alias sunf='echo -n "(•_•) ( •_•)>⌐■-■ (⌐■_■)" | xclip -selection c'
alias nekof='echo -n "ฅ^•ﻌ•^ฅ" | xclip -selection c'

## ???
alias stfu="shutdown 0"
alias please='sudo $(history -p \!\!)' # source: https://www.reddit.com/r/ProgrammerHumor/comments/ikrj2a/yeeeeet/
alias rr='curl -s -L bit.ly/10hA8iC | bash'
## Utiles je crois
alias clear-s="rm -rf ~/.tmux/resurrect & mkdir .tmux/resurrect"
alias scheck="python ~/Projets/cmdNotif/scheck.py"
alias newmd="touch file.md | vim test.md" 
alias internetplz='scheck "ping 1.1.1.1 -c 1" "bytes from" "connection restored, bitch" -i 30'
alias rrs="python /run/media/david/Cours/BA3_BDR/.update.py"
alias dockerup="sudo systemctl start docker"








# Trucs osef
bindkey -v

JAVA_HOME="/usr/lib/jvm/java-11-adoptopenjdk"
